exports.registerModel = require("./register")
exports.leaveManagementModel = require("./leaveManagement")
exports.teamMatesModel = require("./teamMates")
exports.publicHolidayModel = require("./publicHoliday")
exports.statusManagementModel = require("./statusManagement")
exports.taskAssignModel = require("./taskAssign")